language: php

matrix:
    fast_finish: true

    include:
        - php: '5.6'
        - php: '7.0'
        - php: '7.1'
        - php: '7.2'
        - php: 'nightly'

    allow_failures:
        - php: 'nightly'

sudo: false

script:
  - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
